#!/bin/bash

yt_version="version: v0.2.9, date: Tue June 23, 2026"

# Browser priority list for cookie fallback
BROWSERS=("firefox" "chrome" "brave" "edge" "vivaldi")

# Common yt-dlp options
YT_COMMON_OPTS=(
    --no-mtime
    --downloader aria2c
    --remote-components ejs:github
)

show_version() {
    echo ""
    echo "   yt $yt_version"
    echo ""
}

show_help() {
    echo '----------------+-------------------------+-----------------------------------'
    echo ' Commands       | Alias                   | Description'
    echo '----------------+-------------------------+-----------------------------------'
    echo ' yt "<URL>"     | 1080 "<URL>"            | Download best mp4 (1080p to lower)'
    echo ' yt 1080 "<URL>"|                         | Download 1080p mp4'
    echo ' yt 720 "<URL>" |                         | Download 720p mp4'
    echo ' yt 480 "<URL>" |                         | Download 480p mp4'
    echo ' yt 360 "<URL>" |                         | Download 360p mp4'
    echo ' yt 240 "<URL>" |                         | Download 240p mp4'
    echo ' yt mp3 "<URL>" |                         | Download best mp3'
    echo ' yt help        | -h, --help              | To see this help page'
    echo ' yt version     | -v, -version, --version | Check yt version'
    echo ' yt upgrade     | -u, up                  | Upgrade yt (self-reinstallation)'
    echo '----------------+-------------------------+-----------------------------------'
}

run_ytdlp_with_cookies() {
    local quality="$1"
    shift
    local URLs=("$@")

    for url in "${URLs[@]}"; do

        for browser in "${BROWSERS[@]}"; do
            echo "🍪 Trying cookies from: $browser"

            yt-dlp \
                "${YT_COMMON_OPTS[@]}" \
                --cookies-from-browser "$browser" \
                -o "%(title)s.%(ext)s" \
                "$quality" \
                "$url" && break
        done
    done
}

download_video() {
    local quality="$1"
    shift
    local URLs=("$@")

    if [ "$quality" != "mp3" ]; then
        mkdir -p "$HOME/Downloads/Video/"
        cd "$HOME/Downloads/Video/" || exit
    else
        mkdir -p "$HOME/Downloads/Music/"
        cd "$HOME/Downloads/Music/" || exit
    fi

    case "$quality" in
        "720")
            run_ytdlp_with_cookies \
                '-f bv*[height<=1280][ext=mp4][vcodec^=avc1]+ba*[ext=m4a]' \
                "${URLs[@]}"
            ;;
        "480")
            run_ytdlp_with_cookies \
                '-f bv*[height<=854][ext=mp4][vcodec^=avc1]+ba*[ext=m4a]' \
                "${URLs[@]}"
            ;;
        "360")
            run_ytdlp_with_cookies \
                '-f bv*[height<=640][ext=mp4][vcodec^=avc1]+ba*[ext=m4a]' \
                "${URLs[@]}"
            ;;
        "240")
            run_ytdlp_with_cookies \
                '-f bv*[height<=426][ext=mp4][vcodec^=avc1]+ba*[ext=m4a]' \
                "${URLs[@]}"
            ;;
        "mp3")
            for url in "${URLs[@]}"; do
                for browser in "${BROWSERS[@]}"; do
                    yt-dlp \
                        "${YT_COMMON_OPTS[@]}" \
                        --cookies-from-browser "$browser" \
                        --extract-audio \
                        --audio-format mp3 \
                        -o "%(title)s.%(ext)s" \
                        -f bestaudio[ext=m4a]/bestaudio \
                        "$url" && break
                done
            done
            ;;
        *)
            run_ytdlp_with_cookies \
                '-f bv*[height<=1920][ext=mp4][vcodec^=avc1]+ba*[ext=m4a]' \
                "${URLs[@]}"
            ;;
    esac
}

# Main script
if [ -z "$1" ]; then
    exit
fi

case "$1" in
    "-h" | "--help" | "help")
        show_help
        ;;
    "-v" | "version" | "-version" | "--version")
        show_version
        ;;
    "-u" | "up" | "upgrade")
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && brew update && brew upgrade && brew install git python ffmpeg aria2 deno yt-dlp && brew cleanup --prune=all && cd "$HOME" || exit && rm -rf "./yt/" && git clone -b macOS --depth 1 https://github.com/RellikJaeger/yt && mkdir -p "$HOME/.local/bin" && source "$HOME/.zshrc" && mv "./yt/yt" "$HOME/.local/bin/yt" && chmod a+x "$HOME/.local/bin/yt" && rm -rf "./yt/" && clear && yt -v && yt -h
        ;;
    *)
        download_video "$@"
        ;;
esac
